name: Build-Professional-APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build APK (Fullscreen Mode)
        uses: valeriospagnoli/web-to-apk-action@v1.1
        with:
          app-name: "ALDON-PRO"
          # تأكد إن الرابط ده هو رابط موقعك على جيت هاب
          app-url: "https://mohabsobhy132-tech.github.io/Aldon-/" 
          display-mode: "fullscreen"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ALDON-PRO-OFFICIAL-APK
          path: ./*.apk
