name: Build-APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android APK
        uses: tttstudios/html-to-apk-action@v1.0.0
        with:
          app_name: "ALDON-PRO"
          bundle_id: "com.mohab.aldon"
          web_dir: "."

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ALDON-APK
          path: ./*.apk
